# Generated by Django 5.1.1 on 2025-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iX8bFOg7fP84NWm9dLzi5xFttpPxiA2t', editable=False, max_length=32, unique=True),
        ),
    ]
